package com.model;

/**
 * TShipin generated by MyEclipse Persistence Tools
 */

public class TShipin implements java.io.Serializable
{

	private Integer shipinId;
	private String shipinName;
	private String shipinJianjie;
	private String fujian;

	private String fujianYuanshiming;
	private String shijian;
	private String del;
	
	public String getDel()
	{
		return del;
	}
	public void setDel(String del)
	{
		this.del = del;
	}
	public String getFujian()
	{
		return fujian;
	}
	public void setFujian(String fujian)
	{
		this.fujian = fujian;
	}
	public String getFujianYuanshiming()
	{
		return fujianYuanshiming;
	}
	public void setFujianYuanshiming(String fujianYuanshiming)
	{
		this.fujianYuanshiming = fujianYuanshiming;
	}
	public String getShijian()
	{
		return shijian;
	}
	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}
	public Integer getShipinId()
	{
		return shipinId;
	}
	public void setShipinId(Integer shipinId)
	{
		this.shipinId = shipinId;
	}
	public String getShipinJianjie()
	{
		return shipinJianjie;
	}
	public void setShipinJianjie(String shipinJianjie)
	{
		this.shipinJianjie = shipinJianjie;
	}
	public String getShipinName()
	{
		return shipinName;
	}
	public void setShipinName(String shipinName)
	{
		this.shipinName = shipinName;
	}
	
}